Repository carbynestack/ephemeral, pull requests merged in 2022-05, with the labels that each got.

#23 Replace public token with one-time token
  .github/workflows/build-and-test.yaml
Labels: bug, enhancement

#15 update to new mp spdz version
  .ko.yaml
  cmd/discovery/main_test.go
  cmd/ephemeral/main_test.go
  pkg/ephemeral/fake_spdz_test.go
  pkg/ephemeral/io/carrier.go
  pkg/ephemeral/io/carrier_test.go
  pkg/ephemeral/io/feeder.go
  pkg/ephemeral/io/feeder_test.go
  pkg/ephemeral/player.go
  pkg/ephemeral/server.go
  pkg/ephemeral/spdz.go
  pkg/ephemeral/spdz_test.go
  pkg/utils/os.go
  pkg/utils/os_test.go
Labels: enhancement

#25 Fix concurrency issue in client that creates a deadlock
  ephemeral-java-client/src/main/java/io/carbynestack/ephemeral/client/EphemeralClient.java
  ephemeral-java-client/src/main/java/io/carbynestack/ephemeral/client/EphemeralMultiClient.java
  ephemeral-java-client/src/test/java/io/carbynestack/ephemeral/client/EphemeralClientTest.java
  ephemeral-java-client/src/test/java/io/carbynestack/ephemeral/client/EphemeralMultiClientTest.java
Labels: bug
